[workspace]
include = ["**/*.md", "**/*.markdown"]
exclude = ["node_modules/**", "**/tmp/**"]

[diagnostics]
enabled = true
ignored = ["frontmatter-missing"]
level = "warning"

[server]
completion = true
hover = true
references = true
symbol_search = false

