# /qompassai/Diver/stylua.toml
# ---------------------------------
# Copyright (C) 2025 Qompass AI, All rights reserved

call_parentheses = "Always"
collapse_simple_statement = "Never"
column_width = 120
indent_type = "Spaces"
indent_width = 4
line_endings = "Unix"
quote_style = "AutoPreferDouble"
space_after_function_names = "Never"
syntax = "LuaJIT"
