# /qompassai/Diver/vim.toml
# ---------------------------------
# Copyright (C) 2025 Qompass AI, All rights reserved
[describe]
args = [{ type = "string" }, { type = "function" }]

[it.args]
type = "string"
[it.args]
type = "function"

[before_each.args]
type = "function"

[after_each.args]
type = "function"

[vim.api]
any = true

[vim.fn]
any = true

[vim.keymap]
any = true

[vim.lsp]
any = true
