--- Completion option types — type-checker dictionary (never runs).
---
--- Plain-language version: this file never runs -- Neovim never loads it at startup. It is a dictionary of shapes
--- (type annotations) for the lua-language-server type checker, so the editor can offer completions and catch
--- mistakes while you edit. Think of it as the answer key the teacher uses, not a lesson.
---@module 'types.core.cmp'
-- cmp.lua
-- Qompass AI - [ ]
-- Copyright (C) 2026 Qompass AI, All rights reserved
-- ----------------------------------------
---@meta
---@class blink.cmp.Context
---@field bufnr                                            integer
---@field cursor { line: integer, col: integer }
---@class blink.cmp.CompletionItem
---@field kind integer|nil
---@class blink.cmp.SourceProviderConfig
---@field name string
---@field module string
---@field transform_items fun(ctx: blink.cmp.Context, items: blink.cmp.CompletionItem[]): blink.cmp.CompletionItem[]|nil
---@field kind                                string|nil
---@class blink.cmp.SourcesConfig
---@field default                             string[]|nil
---@field compat                              string[]|nil
---@field providers                           table<string, blink.cmp.SourceProviderConfig>|nil
---@class blink.cmp.SnippetsConfig
---@field preset                              string|nil
---@field expand                              fun(opts: any): any
---@class blink.cmp.KeymapConfig
---@field preset                              string|nil
---@class blink.cmp.Config
---@field snippets                             blink.cmp.SnippetsConfig|nil
---@field sources                              blink.cmp.SourcesConfig|nil
---@field keymap                               blink.cmp.KeymapConfig|nil
