-- /qompassai/Diver/lua/types/core/lint.lua
-- Qompass AI Diver Linter Types Config
-- Copyright (C) 2025 Qompass AI, All rights reserved
-- ----------------------------------------
---@meta
---@alias vim.lint.Stream
---| 'stdout'
---| 'stderr'
---| 'both'
---@class vim.lint.Context
---@field bufnr integer
---@field cwd string
---@field filename string
---@field filetype string
---@class vim.lint.Config
---@field cmd string
---@field append_fname? boolean
---@field args? string[]|fun(context: vim.lint.Context): string[]
---@field cwd? string|fun(context: vim.lint.Context): string
---@field env? table<string, string|number>
---@field errorformat? string|string[]
---@field ignore_exitcode? boolean
---@field name? string
---@field parser? fun(output: string, bufnr: integer): vim.Diagnostic.Set[]
---@field stdin? boolean
---@field stream? vim.lint.Stream
---@field timeout? integer
---@class vim.lint.LintProc
---@field bufnr integer
---@field cancelled boolean
---@field ns integer
---@field proc vim.SystemObj
---@field stream vim.lint.Stream
---@alias vim.lint.Config.Report vim.lint.Config.ReportItem[]
---@class vim.lint.Config.ReportItem
---@field code? string|integer
---@field column? integer|string
---@field file_name? string
---@field kind? string
---@field level? string
---@field line? integer|string
---@field message? string
---@field msg? string
---@field path? string
---@field severity? string|vim.diagnostic.Severity
---@field start_col? integer
---@class vim.lint.TSQueryConfig : vim.lint.Config
---@field captures? table<string, vim.diagnostic.Severity>
---@field name string
---@field query string

