-- /qompassai/Diver/lua/types/lsp.lua
-- Qompass AI Diver Core LSP
-- Copyright (C) 2025 Qompass AI, All rights reserved
-- --------------------------------------------------
---@meta
---@module 'types.core.lsp'
---@class                                                                   vim.lsp.Config
---@field additionalArgs?                                                   string[]
---@field args?                                                             string[]
---@field autostart?                                                        boolean
---@field backgroundAnalysisMaxFiles?                                       integer
---@field capabilities?                                                     lsp.ClientCapabilities|table
---@field caseIndent?                                                       boolean
---@field enable?                                                           boolean
---@field enabled?                                                          boolean|string[]
---@field executablePath?                                                   string
---@field explainshellEndpoint?                                             string|nil
---@field fallbackFlags?                                                    string[]
---@field funcNextLine?                                                     boolean
---@field globPattern?                                                      string
---@field indent?                                                           integer
---@field ignoreEditorconfig?                                               boolean
---@field keepPadding?                                                      boolean
---@field languageDialect?                                                  string
---@field logLevel?                                                         string
---@field maxNumberOfProblems?                                              integer
---@field name?                                                             string
---@field offsetEncoding?                                                   string[]
---@field on_attach?                                                        fun(client: vim.lsp.Client, bufnr: integer)
---@field onOpenAndSave?                                                    boolean
---@field path?                                                             string|nil
---@field simplifyCode?                                                     boolean
---@field single_file_support?                                              boolean
---@field spaceRedirects?                                                   boolean
---@field textDocument?                                                     lsp.TextDocumentIdentifier
---@class vim.lsp.Config.CodeLensModule
---@field clear?                                                            fun(client_id?: integer, bufnr?: integer)
---@field display?                                                          fun(lenses?: lsp.CodeLens[], bufnr: integer, client_id: integer)
---@field get?                                                              fun(bufnr: integer): lsp.CodeLens[]
---@field on_codelens?                                                      fun(err: lsp.ResponseError?, result: lsp.CodeLens[], ctx: lsp.HandlerContext)
---@field refresh?                                                          fun(opts?: { bufnr?: integer })
---@field run?                                                              fun()
---@field save?                                                             fun(lenses?: lsp.CodeLens[], bufnr: integer, client_id: integer)
---@class vim.lsp.Config.CompletionEnableOpts
---@field autotrigger?                                                      boolean
---@field cmp?                                                              fun(a: table, b: table): boolean
---@field convert?                                                          fun(item: lsp.CompletionItem): table
---@class vim.lsp.Config.CompletionGetOpts
---@field ctx?                                                              lsp.CompletionContext
---@class vim.lsp.Config.CompletionModule
---@field enable?                                                           fun(enable: boolean, client_id: integer, bufnr: integer, opts?: vim.lsp.Config.CompletionEnableOpts)
---@class vim.lsp.Config.init_options
---@field completionDisableFilterText?                                      boolean
---@field createBaconPreferencesFile?                                       boolean
---@field locationsFile?                                                    string
---@field plugins?                                                          { name: string, location: string, languages?: string[] }
---@field runBaconInBackground?                                             boolean
---@field runBaconInBackgroundCommandArguments?                             string
---@field synchronizeAllOpenFilesWaitMillis?                                integer
---@field updateOnSave?                                                     boolean
---@field useBaconBackend                                                   boolean
---@field updateOnSaveWaitMillis?                                           integer
---@field validateBaconPreferences?                                         boolean
---@class vim.lsp.Config.init_options.preferences
---@field allowIncompleteCompletions?                                       boolean
---@field autoImportFileExcludePatterns?                                    string|nil
---@field autoImportSpecifierExcludeRegexes?                                string|nil
---@field disableSuggestions?                                               boolean
---@field importModuleSpecifierEnding?                                      'auto' | 'minimal' | 'index' | 'js'
---@field includeInlayParameterNameHints?                                   'all' | 'literals' | 'none'
---@field includePackageJsonAutoImports?                                    'auto' | 'off' | 'on'
---@field importModuleSpecifierPreference?                                  'shortest' | 'project-relative' |'relative' | 'non-relative'
---@field jsxAttributeCompletionStyle?                                      'auto' | 'braces' | 'none'
---@field organizeImportsIgnoreCase?                                        'auto' | boolean
---@field organizeImportsCollation?                                         'ordinal' | 'unicode'
---@field organizeImportsCaseFirst?                                         'upper' | 'lower' | 'false'
---@field organizeImportsLocale?                                            'auto' | 'en'
---@field organizeImportsTypeOrder?                                         'last' | 'inline' | 'first'
---@field quotePreference?                                                  'auto' | 'double' | 'single'
---@class vim.lsp.Config.init_options.tsserver
---@field fallbackPath?                                                     string|nil
---@field logDirectory?                                                     string|nil
---@field logVerbosity?                                                     'off' | 'normal' | 'requestTime' | 'terse' | 'verbose'
---@field path?                                                             string|nil
---@field trace?                                                            'messages' | 'off' | 'verbose'
---@field useSyntaxServer?                                                  'auto' | 'never'
---@class vim.lsp.Config.Settings
---@field ansible.ansible.path?                                             string
---@field ansible.ansible.reuseTerminal?                                    boolean
---@field ansible.ansible.useFullyQualifiedCollectionNames?                 boolean
---@field ansible.ansibleServer.trace.server?                               'message' | 'off' | 'verbose'
---@field ansible.completion.provideModuleOptions?                          boolean
---@field ansible.completion.provideModuleParameters?                       boolean
---@field ansible.completion.provideRedirectModules?                        boolean
---@field idris2Lsp.logFile                                                 string|nil
---@field idris2Lsp.logSeverity                                             'Debug'|'Info'|'Warning'|'Error'
---@field ltex.additionalRules.enablePickyRules?                            boolean
---@field ltex.additionalRules.languageModel?                               string
---@field ltex.additionalRules.motherTongue?                                string
---@field basedpyright.analysis?                                            vim.lsp.Config.BasedPyright.Analysis
---@field implicitProjectConfiguration?                                     'amd'|'commonjs'|'es6/es2015'|'es2020'|'esnext'| 'node16'|'node18'|'node20'|'nodenext'|'none'| 'preserver'| 'system'|'umd'
---@field ltex.bibtex.fields?                                               { [string]: boolean } ---object
---@field ltex.checkFrequency?                                              'edit' | 'manual' | 'save'
---@field ltex.clearDiagnosticsWhenClosingFile?                             boolean
---@field ltex.completionEnabled?                                           boolean
---@field ltex.configurationTarget?                                         { [string]: boolean } ---object
---@field ltex.diagnosticSeverity                                           string | { [string]: boolean }
---@field ltex.java.maximumHeapSize?                                        integer
---@field ltex.java.path?                                                   string
---@field ltex.languageToolOrg.username?                                    string
---@field ltex.latex.environments?                                          { [string]: boolean } ---object
---@field ltex.ltex_ls.logLevel?                                            'severe' | 'warning' | 'info' | 'config' | 'fine'| 'finer' | 'finest'
---@field ltex.ltex_ls.path?                                                string
---@field ltex.markdown.nodes?                                              { [string]: boolean } ---object
---@field basedpyright.python?                                              { pythonPath: string }
---@field ltex.statusBarItem?                                               boolean
---@field ltex.trace.server?                                                'off' | 'messages' | 'verbose'
---@field typescript.format.baseIndentSize?                                 integer
---@field typescript.format.convertTabsToSpaces?                            boolean
---@field typescript.format.indentStyle?                                    'Block' | 'None' | 'Smart'
---@field typescript.format.semicolons?                                     'ignore' | 'insert' | 'remove'
---@field redhat.telemetry.enable?                                          boolean
---@field yaml.format.enable?                                               boolean
---@field yaml.format.proseWrap?                                            'always'|'preserve'|'never'|
---@field yaml.http.proxy?                                                  string
---@field yaml.http.proxyStrictSSL?                                         boolean
---@field yaml.style.flowMapping?                                           'allow'|'forbid'
---@field yaml.style.flowSequence?                                          'allow'|'forbid'
---@field yaml.yamlVersion?                                                 '1.2'|'1.1'
---@class HlOpts
---@field bg?                                                               string
---@field bold?                                                             boolean
---@field fg?                                                               string
---@field italic?                                                           boolean
---@field sp?                                                               string
---@field undercurl?                                                        boolean
---@field underline?                                                        boolean
---@field get?                                                              fun(opts?: vim.lsp.Config.CompletionGetOpts)
---@class vim.lsp.Config.LspModule
---@field codelens?                                                         vim.lsp.Config.CodeLensModule
---@field completion?                                                       vim.lsp.Config.CompletionModule
---@class VimExtendedLsp : vim.lsp.Config.LspModule
---@class VimExtendedAPI
---@field lsp                                                               VimExtendedLsp
---@class NvimApi
---@field nvim_set_hl                                                       fun(ns_id: integer, name: string, val: HlOpts)
---@lsp.mod.deprecated                                                      gui=strikethrough
---@lsp.typemod.function.async                                              guifg=Pink
---@class vim.lsp.Config.BasedPyright.Analysis
---@field basedpyright.autoFormatStrings?                                   boolean
---@field basedpyright.autoSearchPaths?                                     boolean
---@field basedpyright.diagnosticMode?                                      'openFilesOnly'|'workspace'
---@field basedpyright.analysis.typeCheckingMode?                           BasedPyright.TypeCheckingMode
---@field useLibraryCodeForTypes?                                           boolean
---@field inlayHints                                                        { variableTypes: boolean, callArgumentNames: boolean, callArgumentNamesMatching: boolean, functionReturnTypes: boolean, genericTypes: boolean }
---@field useTypingExtensions?                                              boolean
---@field fileEnumerationTimeout?                                           integer
---@field basedpyright.analysis.stubPath?                                   string
---@field basedpyright.analysis.typeshedPaths?                              string[]
---@field diagnosticSeverityOverrides?                                      table<string, string>
---@field failOnWarnings?                                                   boolean
---@field reportUnreachable?                                                boolean|string
---@field reportAny?                                                        boolean|string
---@field reportIgnoreCommentWithoutRule?                                   boolean|string
---@field reportPrivateLocalImportUsage?                                    boolean|string
---@field reportImplicitRelativeImport?                                     boolean|string
---@field reportInvalidCast?                                                boolean|string
---@field reportUnsafeMultipleInheritance?                                  boolean|string
---@field reportUnusedParameter?                                            boolean|string
---@field reportImplicitAbstractClass?                                      boolean|string
---@field reportUnannotatedClassAttribute?                                  boolean|string
---@alias BasedPyright.TypeCheckingMode
---| 'off'
---| 'basic'
---| 'standard'
---| 'strict'
---| 'recommended'
---| 'all'
---@class RaRunnableArgs
---@field cargoArgs                                                         string[]
---@field executableArgs?                                                   string[]
---@field cwd                                                               string
---@class RaRunnable
---@field kind                                                              string
---@field label                                                             string
---@field args                                                              RaRunnableArgs