-- /qompassai/Diver/lua/types/core/plugins.lua
-- Qompass AI Diver Core Plugin Types
-- Copyright (C) 2025 Qompass AI, All rights reserved
-- ----------------------------------------
---@meta
---@alias vim.pack.SpecList vim.pack.Spec[]
---@class             vim.pack.Spec
---@field build?                          string|fun()
---@field config?                         fun()
---@field dependencies?                   vim.pack.Spec[]
---@field filetypes?                      string[]
---@field hook?                           fun(spec: vim.pack.Spec)
---@field init?                           fun()
---@field opt?                            boolean
