-- ~/qompassai/Diver/lua/config/core/filetype.lua
-- Qompass AI Diver Core FileType Config
-- Copyright (C) 2025 Qompass AI, All rights reserved
-- ---------------------------------------------------
vim.filetype.add({
    extension = {
        antlers = 'antlers',
        blade = 'blade',
        bri = 'brioche',
        brioche = 'brioche',
        cairo = 'cairo',
        cjs = 'javascript',
        clar = 'clar',
        clarity = 'clarity',
        comp = 'glsl',
        cr = 'crystal',
        cypher = 'cypher',
        edge = 'edge',
        ejs = 'ejs',
        erb = 'eruby',
        frag = 'glsl',
        geom = 'glsl',
        gohtmltmpl = 'gohtmltmpl',
        hbs = 'html.handlebars',
        handlebars = 'html.handlebars',
        handlebars = 'handlebars',
        jsx = 'javascriptreact',
        leaf = 'leaf',
        mdx = 'mdx',
        mjs = 'javascript',
        njk = 'njk',
        nunjucks = 'nunjucks',
        razor = 'razor',
        rst = 'rst',
        schelp = 'scdoc',
        slim = 'slim',
        sugarss = 'sugarss',
        svh = 'systemverilog',
        tesc = 'glsl',
        tese = 'glsl',
        ts = 'typescript',
        tsx = 'typescriptreact',
        v = 'verilog',
        verilog = 'verilog',
        vh = 'verilog',
        yaml = 'yaml',
        yml = 'yaml',
        ['yaml.ansible'] = 'yaml.ansible',
        ['yml.ansible'] = 'yaml.ansible',
        ziggy = 'ziggy',
        ['ziggy-schema'] = 'ziggy_schema',
    },
    filename = {
        ['ansible.cfg'] = 'ansible',
        brioche = 'brioche',
        Cairo = 'cairo',
        Crystal = 'crystal',
        ['.eslintrc.js'] = 'javascript',
        ['.eslintrc.cjs'] = 'javascript',
        ['project.bri'] = 'brioche',
        ['tsconfig.json'] = 'jsonc',
    },
    pattern = {
        ['.*/.*%.als'] = 'alloy',
        ['.*%.ansible%.ya?ml'] = 'yaml.ansible',
        ['.*%.antlers%.html'] = 'html.antlers',
        ['.*%.blade%.php'] = 'blade',
        ['.*%.cairo'] = 'cairo',
        ['.*%.clar'] = 'clar',
        ['.*%.clarity'] = 'clarity',
        ['.*%.crystal'] = 'crystal',
        ['.*%.d.ts'] = 'typescript',
        ['.*%.edge'] = 'edge',
        ['.*%.eex'] = 'html-eex',
        ['^.*/gitconfig.*$'] = 'gitconfig',
        ['^.*/gitignore.*$'] = 'gitignore',
        ['^.*/gitcommit.*$'] = 'gitcommit',
        ['.*/%.github[%w/]+workflows[%w/]+.*%.ya?ml'] = 'yaml.github',
        ['%.gitlab%-ci%.ya?ml'] = 'yaml.gitlab',
        ['*.gjs'] = 'javascript.glimmer',
        ['*.gts'] = 'typescript.glimmer',
        ['.*%.heex'] = 'html-eex',
        ['.*%.html%.antlers'] = 'html.antlers',
        ['.*%.postcss'] = 'postcss',
        ['.*%.razor'] = 'razor',
        ['.*%.sugarss'] = 'sugarss',
        ['.*/templates/.*%.yaml'] = 'helm',
        ['.*/templates/.*%.yml'] = 'helm',
        ['.*/templates/.*%.tpl'] = 'helm',
        ['tsconfig.*%.json'] = 'jsonc',
        ['.*/values.*%.ya?ml'] = 'yaml.helm-values',
    },
})