-- /qompassai/Diver/lua/config/core/tree.lua
-- Qompass AI Diver TreeSitter Config Module
-- Copyright (C) 2025 Qompass AI, All rights reserved
------------------------------------------------------
local M = {}
local register = vim.treesitter.language.register

function M.treesitter(opts)
    opts = opts or {}
    local install = require('nvim-treesitter.install')
    local parsers = require('nvim-treesitter.parsers')
    local configs = require('nvim-treesitter.configs')

    install.prefer_git = true

    local parser_config = parsers.get_parser_configs()

    parser_config.objc = {
        install_info = {
            url = 'https://github.com/merico-dev/tree-sitter-objc',
            files = { 'src/parser.c' },
            branch = 'main',
            generate_requires_npm = false,
            requires_generate_from_grammar = false,
        },
        filetype = 'objc',
    }

    local base_config = {
        auto_install = true,
        ensure_installed = {
            'ada',
            'agda',
            'angular',
            'apex',
            'arduino',
            'asm',
            'astro',
            'awk',
            'bash',
            'bass',
            'beancount',
            'bibtex',
            'bicep',
            'bitbake',
            'blade',
            'blueprint',
            'c',
            'c_sharp',
            'caddy',
            'cairo',
            'clojure',
            'cmake',
            'comment',
            'commonlisp',
            'cpp',
            'css',
            'csv',
            'cuda',
            'cue',
            'd',
            'dart',
            'desktop',
            'devicetree',
            'diff',
            'dockerfile',
            'dot',
            'doxygen',
            'editorconfig',
            'eex',
            'elixir',
            'elm',
            'embedded_template',
            'erlang',
            'facility',
            'faust',
            'fennel',
            'fish',
            'foam',
            'fortran',
            'fsh',
            'fsharp',
            'func',
            'gap',
            'gdscript',
            'gdshader',
            'gitattributes',
            'git_config',
            'git_rebase',
            'gitignore',
            'gleam',
            'glsl',
            'go',
            'goctl',
            'godot_resource',
            'gomod',
            'gosum',
            'gotmpl',
            'gowork',
            'gpg',
            'graphql',
            'gstlaunch',
            'hack',
            'haskell',
            'hcl',
            'helm',
            'hlsl',
            'hoon',
            'html',
            'htmldjango',
            'hyprlang',
            'idl',
            'idris',
            'inko',
            'ini',
            'java',
            'javadoc',
            'jinja',
            'jq',
            'jsdoc',
            'json',
            'json5',
            'jsonc',
            'julia',
            'just',
            'kcl',
            'kconfig',
            'kotlin',
            'latex',
            'llvm',
            'lua',
            'luadoc',
            'luap',
            'luau',
            'm68k',
            'make',
            'markdown',
            'markdown_inline',
            'matlab',
            'mermaid',
            'meson',
            'mlir',
            'muttrc',
            'nginx',
            'ninja',
            'nix',
            'norg',
            'objc',
            'objdump',
            'ocaml',
            'ocaml_interface',
            'ocamllex',
            'odin',
            'passwd',
            'pem',
            'perl',
            'php',
            'php_only',
            'phpdoc',
            'po',
            'powershell',
            'printf',
            'properties',
            'proto',
            'puppet',
            'pymanifest',
            'python',
            'query',
            'r',
            'regex',
            'rego',
            'requirements',
            'rescript',
            'robot',
            'robots',
            'roc',
            'rst',
            'ruby',
            'rust',
            'scala',
            'scfg',
            'scheme',
            'scss',
            'smithy',
            'solidity',
            'sql',
            'ssh_config',
            'starlark',
            'supercollider',
            'superhtml',
            'svelte',
            'sway',
            'swift',
            'tablegen',
            'tcl',
            'teal',
            'templ',
            'terraform',
            'textproto',
            'tiger',
            'tmux',
            'toml',
            'tsv',
            'tsx',
            'turtle',
            'typescript',
            'typst',
            'udev',
            'usd',
            'v',
            'vala',
            'verilog',
            'vhdl',
            'vim',
            'vimdoc',
            'vue',
            'wgsl',
            'wgsl_bevy',
            'xcompose',
            'xml',
            'yaml',
            'yang',
            'zathurarc',
            'zig',
            'ziggy',
            'ziggy_schema',
        },

        ignore_install = {},

        highlight = {
            enable = true,
            additional_vim_regex_highlighting = false,
        },

        indent = {
            enable = true,
        },

        incremental_selection = {
            enable = true,
            keymaps = {
                init_selection = 'gnn',
                node_incremental = 'grn',
                scope_incremental = 'grc',
                node_decremental = 'grm',
            },
        },

        textobjects = {
            move = {
                enable = true,
                set_jumps = true,

                goto_next_start = {
                    [']c'] = '@class.outer',
                    [']i'] = '@conditional.outer',
                    [']l'] = '@loop.outer',
                    [']m'] = '@function.outer',
                    [']s'] = {
                        query = '@scope',
                        query_group = 'locals',
                        desc = 'Next scope',
                    },
                    [']z'] = {
                        query = '@fold',
                        query_group = 'folds',
                        desc = 'Next fold',
                    },
                },

                goto_next_end = {
                    [']C'] = '@class.outer',
                    [']F'] = '@call.outer',
                    [']I'] = '@conditional.outer',
                    [']L'] = '@loop.outer',
                    [']M'] = '@function.outer',
                },

                goto_previous_start = {
                    ['[c'] = '@class.outer',
                    ['[f'] = '@call.outer',
                    ['[i'] = '@conditional.outer',
                    ['[l'] = '@loop.outer',
                    ['[m'] = '@function.outer',
                },

                goto_previous_end = {
                    ['[C'] = '@class.outer',
                    ['[F'] = '@call.outer',
                    ['[I'] = '@conditional.outer',
                    ['[L'] = '@loop.outer',
                    ['[M'] = '@function.outer',
                },
            },
        },
    }

    local config = vim.tbl_deep_extend('force', base_config, opts)
    configs.setup(config)

    register('bash', 'zsh')
    register('markdown', 'mdx')
end

return M
