-- tests/busted/unit/budget_spec.lua
-- Spec for ai.harness.budget: per-run hard loop limits.
-- 6 validation + 6 adversarial = 12 tests.
-- Run from repo root: busted --run=unit tests/busted/unit/budget_spec.lua

local budget = require('ai.harness.budget')

describe('ai.harness.budget', function()
    describe('validation', function()
        it('creates a budget with usage zeroed', function()
            local b, err = budget.new({ turn = 10, token = 1000 })
            assert.is_truthy(b, tostring(err))
            assert.are.equal(10, b.limits.turn)
            assert.are.equal(1000, b.limits.token)
            assert.are.equal(0, b.used.turn)
            assert.are.equal(0, b.used.token)
        end)

        it('checks consumption that fits within limits', function()
            local b = assert(budget.new({ turn = 3 }))
            assert.is_true(budget.check(b, 'turn', 2))
            assert.is_true(budget.check(b, 'turn', 0))
        end)

        it('consumes and shrinks the remaining headroom', function()
            local b = assert(budget.new({ token = 100 }))
            assert.is_true(budget.consume(b, 'token', 30))
            assert.are.equal(70, budget.remaining(b, 'token'))
            assert.are.equal(30, b.used.token)
        end)

        it('returns nil remaining for unlimited kinds', function()
            local b = assert(budget.new({ turn = 5 }))
            assert.is_true(budget.consume(b, 'byte', 999999))
            assert.is_nil(budget.remaining(b, 'byte'))
        end)

        it('reports exhaustion with the exhausted kind', function()
            local b = assert(budget.new({ token = 50 }))
            local exhausted = budget.exhausted(b)
            assert.is_false(exhausted)
            assert.is_true(budget.consume(b, 'token', 50))
            local is_exhausted, kind = budget.exhausted(b)
            assert.is_true(is_exhausted)
            assert.are.equal('token', kind)
        end)

        it('snapshots a copy that survives later mutation', function()
            local b = assert(budget.new({ turn = 4 }))
            budget.consume(b, 'turn', 1)
            local snap = budget.snapshot(b)
            budget.consume(b, 'turn', 2)
            assert.are.equal(4, snap.limits.turn)
            assert.are.equal(1, snap.used.turn)
            assert.are.equal(3, b.used.turn)
        end)
    end)

    describe('adversarial', function()
        it('rejects unknown budget kinds', function()
            local b, err = budget.new({ gold = 10 })
            assert.is_nil(b)
            assert.is_truthy(err:find('unknown budget kind'))
        end)

        it('rejects zero or negative limits', function()
            local b1, err1 = budget.new({ turn = 0 })
            assert.is_nil(b1)
            assert.is_truthy(err1)
            local b2, err2 = budget.new({ turn = -3 })
            assert.is_nil(b2)
            assert.is_truthy(err2)
        end)

        it('rejects non-table limits', function()
            local b, err = budget.new('limits')
            assert.is_nil(b)
            assert.is_truthy(err)
        end)

        it('leaves usage unchanged when consumption exceeds the limit', function()
            local b = assert(budget.new({ turn = 2 }))
            budget.consume(b, 'turn', 1)
            local ok, err = budget.consume(b, 'turn', 5)
            assert.is_false(ok)
            assert.is_truthy(err:find('exhausted'))
            assert.are.equal(1, b.used.turn)
        end)

        it('rejects check on an unknown kind', function()
            local b = assert(budget.new({ turn = 2 }))
            local ok, err = budget.check(b, 'gold', 1)
            assert.is_false(ok)
            assert.is_truthy(err:find('unknown budget kind'))
        end)

        it('rejects negative consumption amounts', function()
            local b = assert(budget.new({ turn = 2 }))
            local ok, err = budget.check(b, 'turn', -1)
            assert.is_false(ok)
            assert.is_truthy(err:find('non%-negative'))
        end)
    end)
end)
