-- /qompassai/Diver/lsp/htmx.lua
-- Qompass AI Htmx LSP Config
-- Copyright (C) 2025 Qompass AI, All rights reserved
-----------------------------------------------------
---@source https://htmx.org/reference/#config | https://github.com/ThePrimeagen/htmx-lsp
return ---@type vim.lsp.Config
{
    cmd = {
        'htmx-lsp',
        '-f',
        vim.fn.stdpath('cache') .. '/htmx-lsp.log',
        '-l',
        'DEBUG',
    },
    filetypes = {
        'aspnetcorerazor',
        'astro',
        'astro-markdown',
        'blade',
        'clojure',
        'django-html',
        'htmldjango',
        'edge',
        'eelixir',
        'elixir',
        'ejs',
        'erb',
        'eruby',
        'gohtml',
        'gohtmltmpl',
        'haml',
        'handlebars',
        'hbs',
        -- 'html',
        'htmlangular',
        'html-eex',
        'heex',
        'jade',
        --'js',
        'leaf',
        'liquid',
        'mixed',
        'mdx',
        'mustache',
        'njk',
        'nunjucks',
        'php',
        'razor',
        'slim',
        'twig',
        'javascript',
        'javascriptreact',
        'reason',
        'rescript',
        'typescript',
        'typescriptreact',
        'vue',
        'svelte',
        'templ',
    },
    on_attach = require('config.core.lsp').on_attach,
    root_markers = {
        '.git',
    },
    settings = {
        htmx = {
            config = {
                addedClass = 'htmx-added',
                allowEval = true,
                allowNestedOobSwaps = true,
                allowScriptTags = false,
                defaultFocusScroll = false,
                defaultSettleDelay = 20,
                defaultSwapDelay = 0,
                defaultSwapStyle = 'innerHTML',
                disableInheritance = true,
                historyCacheSize = 10,
                historyEnabled = true,
                disableSelector = '[hx-disable], [data-hx-disable]',
                getCacheBusterParam = 'false',
                historyRestoreAsHxRequest = true,
                ignoreTitle = false,
                includeIndicatorStyles = true,
                indicatorClass = 'htmx-indicator',
                inlineScriptNonce = '',
                methodsThatUseUrlParams = {
                    'get',
                    'delete',
                    'head',
                },
                reportValidityOfForms = true,
                refreshOnHistoryMiss = false,
                requestClass = 'htmx-request',
                scrollBehavior = 'instant',
                scrollIntoViewOnBoost = true,
                selfRequestsOnly = true,
                settlingClass = 'htmx-settling',
                timeout = 0,
                triggerSpecsCache = nil,
                withCredentials = false,
                wsBinaryType = 'blob',
                wsReconnectDelay = 'full-jitter',
            },
        },
    },
}