# Linux Targets

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--undefined", "-C", "link-arg=dynamic_lookup"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--undefined", "-C", "link-arg=dynamic_lookup"]

[target.armv7-unknown-linux-gnueabihf]
rustflags = ["-C", "link-arg=-Wl,--undefined", "-C", "link-arg=dynamic_lookup"]

[target.arm64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--undefined", "-C", "link-arg=dynamic_lookup"]

[target.amd64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--undefined", "-C", "link-arg=dynamic_lookup"]

[target.dmg64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--undefined", "-C", "link-arg=dynamic_lookup"]

# Windows Targets for MSVC

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/FORCE", "-C", "link-arg=/NODEFAULTLIB"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/FORCE", "-C", "link-arg=/NODEFAULTLIB"]

[target.arm64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/FORCE", "-C", "link-arg=/NODEFAULTLIB"]

[target.amd64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/FORCE", "-C", "link-arg=/NODEFAULTLIB"]

[target.dmg64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/FORCE", "-C", "link-arg=/NODEFAULTLIB"]

[target.armv7-pc-windows-msvc]
rustflags = ["-C", "link-arg=/FORCE", "-C", "link-arg=/NODEFAULTLIB"]

# Windows Targets for GNU (Optional)

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition", "-C", "link-arg=-Wl,--export-all-symbols"]

[target.aarch64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition", "-C", "link-arg=-Wl,--export-all-symbols"]

[target.arm64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition", "-C", "link-arg=-Wl,--export-all-symbols"]

[target.amd64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition", "-C", "link-arg=-Wl,--export-all-symbols"]

[target.dmg64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition", "-C", "link-arg=-Wl,--export-all-symbols"]

[target.armv7-pc-windows-gnu]
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition", "-C", "link-arg=-Wl,--export-all-symbols"]

