# /qompassai/Diver/scripts/msft/wcargo.ps1
# Qompass AI Windows Powershell Cargo Script
# Copyright (C) 2025 Qompass AI, All rights reserved
# =================================================
$ErrorActionPreference = 'Stop'
function Write-Info { Write-Host "INFO: $args" -ForegroundColor Cyan }
function Write-Success { Write-Host "SUCCESS: $args" -ForegroundColor Green }
function Write-Error { Write-Host "ERROR: $args" -ForegroundColor Red }
function Write-Warn { Write-Host "WARN: $args" -ForegroundColor Yellow }
function Fix-CargoSSL {
    Write-Host ""
    if (-not (Get-Command cargo -ErrorAction SilentlyContinue)) {
        Write-Error "Cargo not found. Please install Rust first:"
        Write-Info "Download from: https://rustup.rs/"
        exit 1
    }
    $cargoVersion = (cargo --version)
    Write-Info "Found: $cargoVersion"
    Write-Host ""
    try {
        [Environment]::SetEnvironmentVariable('CARGO_HTTP_CHECK_REVOKE', 'false', 'User')
        $env:CARGO_HTTP_CHECK_REVOKE = 'false'
        Write-Success "Set CARGO_HTTP_CHECK_REVOKE=false"
        [Environment]::SetEnvironmentVariable('CARGO_NET_GIT_FETCH_WITH_CLI', 'true', 'User')
        $env:CARGO_NET_GIT_FETCH_WITH_CLI = 'true'
        Write-Success "Set CARGO_NET_GIT_FETCH_WITH_CLI=true"
    }
    catch {
        Write-Error "Failed to set environment variables: $_"
        exit 1
    }
    Write-Host ""
    if (Get-Command git -ErrorAction SilentlyContinue) {
        try {
            git config --global http.sslBackend schannel
            git config --global http.sslVerify true
            Write-Success "Git configured to use Windows SSL (schannel)"
        }
        catch {
            Write-Warn "Could not configure Git (non-fatal): $_"
        }
    }
    else {
        Write-Warn "Git not found - skipping Git configuration"
        Write-Info "Install Git for better SSL handling: winget install Git.Git"
    }
    Write-Host ""
    $cargoConfigDir = "$env:USERPROFILE\.cargo"
    try {
        if (-not (Test-Path $cargoConfigDir)) {
            New-Item -ItemType Directory -Path $cargoConfigDir -Force | Out-Null
            Write-Success "Created: $cargoConfigDir"
        }
        else {
            Write-Info "Directory already exists: $cargoConfigDir"
        }
    }
    catch {
        Write-Error "Failed to create cargo directory: $_"
        exit 1
    }
    Write-Host ""
    $configPath = "$cargoConfigDir\config.toml"
    $configContent = @'
# Cargo SSL Configuration
# Generated by Fix-CargoSSL.ps1

[http]
check-revoke = false
ssl-version = "tlsv1.2"
timeout = 60

[net]
git-fetch-with-cli = true
retry = 3

[build]
jobs = 4

[source.crates-io]
replace-with = "crates-io"
registry = "https://github.com/rust-lang/crates.io-index"

[registries.crates-io]
protocol = "sparse"
'@

    try {
        if (Test-Path $configPath) {
            $backupPath = "$configPath.backup.$(Get-Date -Format 'yyyyMMdd_HHmmss')"
            Copy-Item -Path $configPath -Destination $backupPath -Force
            Write-Warn "Backed up existing config to: $backupPath"
        }
        Set-Content -Path $configPath -Value $configContent -Force
        Write-Success "Created cargo config: $configPath"
    }
    catch {
        Write-Error "Failed to create config file: $_"
        exit 1
    }
    Write-Host ""
    Write-Info "Installing 'tokei' as a test (small, fast package)..."
    Write-Host ""
    try {
        $output = cargo install tokei --force 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Success "Test package installed successfully!"
            Write-Success "SSL configuration is working!"
        }
        else {
            Write-Warn "Test install completed with warnings"
            Write-Info "Output: $output"
        }
    }
    catch {
        Write-Warn "Test install failed, but config has been applied"
        Write-Info "Try running: cargo install <package-name>"
        Write-Info "If issues persist, see additional options below"
    }
    Write-Host ""
    Write-Host "=== Configuration Summary ===" -ForegroundColor Cyan
    Write-Host "Environment Variables Set:"
    Write-Host "  CARGO_HTTP_CHECK_REVOKE = false"
    Write-Host "  CARGO_NET_GIT_FETCH_WITH_CLI = true"
    Write-Host ""
    Write-Host "Config File: $configPath"
    Write-Host "Backup: $configPath.backup.* (if existed)"
    Write-Host ""
    Write-Host "=== Next Steps ===" -ForegroundColor Cyan
    Write-Host "1. Restart your terminal to load new environment variables"
    Write-Host "2. Try: cargo install ripgrep"
    Write-Host "3. If still failing, run with verbose: cargo install <package> --verbose"
    Write-Host ""
    Write-Host "=== If Issues Persist ===" -ForegroundColor Yellow
    Write-Host "Corporate Network:"
    Write-Host "  - Check with IT about proxy settings"
    Write-Host "  - May need to add company certificate"
    Write-Host ""
    Write-Host "Antivirus:"
    Write-Host "  - Add exclusions for: $env:USERPROFILE\.cargo"
    Write-Host "  - Add exclusions for: $env:USERPROFILE\.rustup"
    Write-Host "  - Temporarily disable SSL scanning"
    Write-Host ""
    Write-Host "Advanced:"
    Write-Host "  - Set HTTP proxy: `$env:HTTP_PROXY='http://proxy:port'"
    Write-Host "  - Set HTTPS proxy: `$env:HTTPS_PROXY='http://proxy:port'"
    Write-Host ""

    Write-Success "Configuration complete! Close and reopen your terminal."
}
try {
    Fix-CargoSSL
}
catch {
    Write-Error "Script failed: $_"
    Write-Info "Stack trace: $($_.ScriptStackTrace)"
    exit 1
}