[
  (parenthesized_statements)
  (call)
  (array)
  ; TODO: these can be statements, but also expressions. Use better captures
  ; for them
  ; (string_array)
  ; (symbol_array)
  ; (hash)
  ; (subshell)
  ; (string)
  ; (character)
  (chained_string)
  (regex)
  (lambda)
  (method)
  (singleton_method)
  (class)
  (singleton_class)
  (module)
  (begin)
  (while)
  (until)
  (if)
  (unless)
  (for)
  (case)
  (case_match)
  (return)
  (yield)
  (break)
  (next)
  (redo)
  (retry)
  (unary)
  (heredoc_beginning)
] @output_statement
