-- media.lua
-- Qompass AI - [ ]
-- Copyright (C) 2026 Qompass AI, All rights reserved
-- ----------------------------------------
---@class rec.State
---@field dispose? fun()
---@field output? string
---@class (exact) rec.Options
---@field fps integer Frames per second
---@field output string Output file path
---@field char_width integer Character width in pixels
---@field char_height integer Character height in pixels
---@field use_font boolean Whether to use font rendering
---@field font_path string Path to font file
---@field address string Neovim server for RPC connection
---@field kind "ffmpeg"|"x264"|"raw" Encoder type
----@param opts? rec.Options|{}
---@type rec.Options
---@return string? output The output file path or nil if not recording
----@param opts? rec.Options
---@return string? output The output file path if stopped, nil otherwise