-- #################################################################
-- /qompassai/Diver/plugin/dir.lua
-- Qompass AI Dir
-- SPDX-License-Identifier: Apache-2.0
-- Copyright (c) 2026 Qompass AI
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at:
--   http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
-- #################################################################
-- Compatibility file for the retired local directory-browser shim.
-- Neovim 0.13 supplies the browser in $VIMRUNTIME/plugin/dir.lua.
-- Do not set its loaded flag or register replacement directory autocommands here.
-- config.nav.nt loads the native plugin from the active runtime when needed.
-- This empty table also keeps existing require('plugins.dir') calls valid.
-- Replace any old copy in plugin/dir.lua or lua/plugins/dir.lua with this file.

return {}
